/* SPDX-License-Identifier: MIT
 * Compatibility names for existing X940 bring-up patches.
 * New code should include ac_mgfx2_regs.h and use its named register enum.
 */
#ifndef AC_X940_REG_V25_H
#define AC_X940_REG_V25_H

#include "ac_mgfx2_regs.h"

static inline unsigned
ac_x940_reg_v25(bool is_xclipse940, unsigned amd_reg, unsigned mgfx2_reg)
{
   return ac_mgfx2_reg(is_xclipse940, amd_reg, (enum ac_mgfx2_reg)mgfx2_reg);
}

#define AC_X940_CB_COLOR0_INFO AC_MGFX2_CB_COLOR0_INFO
#define AC_X940_CB_SHADER_MASK AC_MGFX2_CB_SHADER_MASK
#define AC_X940_DB_EQAA AC_MGFX2_DB_EQAA
#define AC_X940_DB_RENDER_CONTROL AC_MGFX2_DB_RENDER_CONTROL
#define AC_X940_DB_RENDER_OVERRIDE2 AC_MGFX2_DB_RENDER_OVERRIDE2
#define AC_X940_DB_RMI_L2_CACHE_CONTROL AC_MGFX2_DB_RMI_L2_CACHE_CONTROL
#define AC_X940_DB_VRS_OVERRIDE_CNTL AC_MGFX2_DB_VRS_OVERRIDE_CNTL
#define AC_X940_GE_USER_VGPR_EN AC_MGFX2_GE_USER_VGPR_EN
#define AC_X940_PA_SC_CENTROID_PRIORITY_0 AC_MGFX2_PA_SC_CENTROID_PRIORITY_0
#define AC_X940_PA_SC_MODE_CNTL_0 AC_MGFX2_PA_SC_MODE_CNTL_0
#define AC_X940_SPI_BARYC_CNTL AC_MGFX2_SPI_BARYC_CNTL
#define AC_X940_SPI_INTERP_CONTROL_0 AC_MGFX2_SPI_INTERP_CONTROL_0
#define AC_X940_SPI_SHADER_COL_FORMAT AC_MGFX2_SPI_SHADER_COL_FORMAT
#define AC_X940_SPI_SHADER_PGM_HI_LS AC_MGFX2_SPI_SHADER_PGM_HI_LS
#define AC_X940_SPI_SHADER_PGM_RSRC3_HS AC_MGFX2_SPI_SHADER_PGM_RSRC3_HS
#define AC_X940_SPI_SHADER_PGM_RSRC3_PS AC_MGFX2_SPI_SHADER_PGM_RSRC3_PS
#define AC_X940_SPI_SHADER_PGM_RSRC4_HS AC_MGFX2_SPI_SHADER_PGM_RSRC4_HS
#define AC_X940_VGT_REUSE_OFF AC_MGFX2_VGT_REUSE_OFF
#define AC_X940_VGT_TF_MEMORY_BASE_HI AC_MGFX2_VGT_TF_MEMORY_BASE_HI

#endif
